#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf log.*

cd system
python3 script.py
cd ..

runApplication blockMesh
runApplication snappyHexMesh -overwrite

runApplication $(getApplication)
